### PR TITLE
Implemented map view with member markers

### PR DESCRIPTION
**Pull request by excelwebzone**
screen shot 2018-12-27 at 5 51 55 pm

### CODE REVIEW

**Comment by excelwebzone** [comment]
I'm not sure if this `process.env.APP_GOOGLE_MAPS_API_KEY` will work on the client side.. maybe it would be good to use something like `dotenv` for environment variables. What do you think?

**Comment by excelwebzone** [comment]
@jeremija Did you had a chance to review this? Let me know if you want me to make additional changes. Thanks.

**Comment by jeremija** [comment]
Sorry for the delay. I'm afraid I cannot accept this pull request at this point for a number of reasons:

1. I do not see the benefit of using Webpack over browserify. In my experience, Webpack is a lot slower. The "cold start" build speeds have increased from about 3-4 seconds to over 10 seconds on my 16GB Macbook Pro.

2. It looks like the stylesheets do not get generated correctly for the index page.

3. If the Google Maps API key is set, users will get a browser prompt for location access with no explanation, which is not preferred according to [Google Web Fundamentals][gwf]:

   > Make sure that users understand why you’re asking for their location, and what the benefit to them will be. Asking for it immediately on the homepage as the site loads results in a poor user experience.

   Now that I think about it, the reason for the camera/microphone permission should be explained to the user too.

 4. The test coverage has dropped significantly again. Version 2.0.7 had a branch coverage of 98.85%, with the previous pull request it dropped down to 89.57%, and now its down at 82.96%.

Having said all that, I would like to keep Peer Calls a simple project that enables the users to communicat securely, and that works well on most devices.  Support for Google Maps adds a lot of complexity, especially with their [billing model](https://cloud.google.com/maps-platform/pricing/).

Sorry, but I am going to close this.

[gwf]: https://developers.google.com/web/fundamentals/native-hardware/user-location/

**Comment by excelwebzone** [comment]
I understand. Let's keep this project simple.. this enhancement was real for something I needed in another project. Thanks.

**Pull request closed without merging**
