### PR TITLE
Created a simple toolbar

### PR DESCRIPTION
**Pull request by excelwebzone**
- Audio/Video toggling
- Fullscreen
- Hangout (return to homepage)

screen shot 2018-11-22 at 11 33 17 am

### CODE REVIEW

**Comment by excelwebzone** [comment]
TODO: I'm going to add 2 more buttons:
- Chat
- Send Invite

**Comment by excelwebzone** [comment]
screen shot 2018-11-23 at 4 55 10 pm

> Note: I can change the look and feel of the chat if anyone have a better look :-)

**Comment by excelwebzone** [comment]
@jeremija please review PR and merge if all good. Thanks.


**TODO:**
- Make chat icon blink on new message (if close)
- Add invite button - open a popover allowing to enter email or phone

**Comment by excelwebzone** [comment]
The image is a snap-shoot of the user video. If video is not active is will use the initials of the **userId** (`socket.id`)

screen shot 2018-11-24 at 6 47 24 pm

**Comment by excelwebzone** [comment]
@jeremija would you prefer this look? I can easily change it?

screen shot 2018-11-24 at 7 41 27 pm

**Comment by lil5** [comment]
This might finish off those icons #51

**Comment by jeremija** [comment]
Hi @excelwebzone,

Please find my comments below:

1. Moment.js is a very useful library, but the main issue is that the `moment` objects are not immutable. It might not matter in a simple case like this:

```javascript
moment(message.timestamp).fromNow()
```

but it will become an issue in this case:

```javascript
const start = moment()
const end = start.add(1, 'day')
console.log(start.fromNow() + ', ' + end.fromNow())
// prints:      in a day, in a day
// instead of:  a few seconds ago, in a day
```

I'd give [Luxon](https://moment.github.io/luxon/) a try instead (it's from the creators of Moment.js).

2. Calling `document#getElementById` is not idiomatic in React. The preferred way would be to use [refs][refs].

3. Cross-browser support for fullscreen: A library such as [screenfull][sf] might come in handy, because it already handles all of the different use-cases. Then we can simplify our code, and less effort to test it in every browser.

4. CDN. Previously, all dependencies (including fonts) have been bundled with this project. I think whether or not to use a CDN should be decided by the user hosting peer-calls, but we should default to bundling everything with peer-calls. Also, refreshing the page during development with cache disabled can cause slowdowns on slower internet connections (like the one I'm right now, for example). 

5. I like both chat views, but I guess I wouldn't want it to look like a Google Hangouts clone 🙂 

6. The test coverage has dropped significantly:

Current master branch coverage (21e3040):

```
File      |  % Stmts | % Branch |  % Funcs |  % Lines |
----------|----------|----------|----------|----------|
All files |      100 |    98.85 |      100 |      100 |
```

Coverage for this pull request (24eddf0):

```
File      |  % Stmts | % Branch |  % Funcs |  % Lines |
----------|----------|----------|----------|----------|
All files |    88.25 |    74.81 |    87.68 |    87.58 |
```

Do you have any plans to add more tests?

7. Git commit messages (for future reference). You can find the example for writing commit messages in `CONTRIBUTING.md`: [link][commit]. All previous commit messages use the imperative form, and I would like to keep it that way:

> Write your commit message in the imperative: "Fix bug" and not "Fixed bug" or "Fixes bug." This convention matches up with commit messages generated by commands like git merge and git revert.

Another article about that [topic][commit2].

Let me know if you have any questions or comments!

[refs]: https://reactjs.org/docs/refs-and-the-dom.html
[sf]: https://www.npmjs.com/package/screenfull
[commit]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[commit2]: https://chris.beams.io/posts/git-commit/#imperative

**Comment by lil5** [comment]
CDN is something for a different Pull Request

I highly advice not using CDN as it's a security risk

**Comment by excelwebzone** [comment]
For some reason the fonts not loading.. can you guys check why.. thanks.

**Comment by excelwebzone** [comment]
Regarding the usage of `document#getElementById`, I have tried to use `React.createRef()` but I don't think the current version support it.. Any recommendation?

**Comment by excelwebzone** [comment]
> Note: test unit are not my forte.. I would appreciate if you can take over this part  👍

**Comment by jeremija** [comment]
Most likely the fonts aren't loading because the required static assets are not exposed via express. Try adding a line like the following below this line in `app.js`:

```javascript
router.use('/fonts', express.static(path.join(__dirname, '../../node_modules/<fonts_module>/path/to/fonts')))
```

Keep in mind that the fonts we'd still want to be able to load fonts even under a different `baseUrl` (context root), for example from all of the following URLs:

- https://peercalls.com
- https://peercalls.com/call/<call_id>
- https://customdomain.com/peer-calls/
- https://customdomain.com/peer-calls/call/<call_id>

I'm not yet sure if there's an easy way to do this in SCSS without requiring the user to rebuild the scss files if they would like to change the `baseUrl`.

**Comment by lil5** [comment]
`?37351711` is missing!

See original:
https://github.com/jeremija/peer-calls/blob/master/src/scss/_fonts.scss

**Comment by jeremija** [comment]
What's `?37351711`?

**Comment by lil5** [comment]
No idea but it was there originally

**Comment by excelwebzone** [comment]
I tried to improve the test units as much as I could.. check it..

File               |  % Stmts | % Branch |  % Funcs |  % Lines |
-------------------|----------|----------|----------|----------|
All files          |    95.43 |    92.04 |    95.07 |    95.13 |

**Comment by jeremija** [comment]
Thank you @excelwebzone! Will try to review this tomorrow.

**Comment by jeremija** [comment]
@excelwebzone Sorry it took so long to review. This looks awesome, thank you for your contribution!

**Pull request merged**
